version: '3.1'

services:
  web:
    build: .
    ports:
      - "8000:80"
      - "44348:443"
  prometheus:
    build: 
      context: .
      dockerfile: dockerfile-prometheus.yml
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - web
  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3001:3000"   
    depends_on:
      - prometheus